version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    container_name: jenkins
    volumes:
      - /Users/alam.ashraful/Desktop/ashraf-RnD/jenkins-concept/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
#  agent:
#    image: jenkins/ssh-agent:jdk11
#    privileged: true
#    user: root
#    container_name: agent
#    expose:
#      - 22
#    environment:
#      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCdgy7cc/Ro0+wbcDt1nyEK8spb2AjcvFV2NLiGrBKA6/bAanRqPfP7ZAI7WVlinX13/9t4lHr0uVvF4BkJ/qQ/HPD0uu7i83mi5ckz4IYohnTP9U1tLdR9cTPDo9c4m4sNTASTeUsGXxp4BcdjtTo9EngJpJSQSEOyLAIH//8CsSmu5ql3XrGQbt2I0o/c0hnLY4UEJoJ98xiGabzCdlILkMHaL+LHKUZnfzbdCFrb3/84PNNZ7CKZvuGB/1GGt4B6HGYQ0/jHnwGz4uDjfh9bnbCuxrYSgxBYWMwfDeTooKylY5KhF1cPsQ3bbNon9aRvACdLHl6ZcYboIdTr5dcj0nxrvO4CTm03+K+ZWO430/6+1BpPdt16YCmTBjnWMXQ23rxZ1cEgZWNJkWe/zXAJE0GaQoHlApnVnIRLciBsF5SVYFb2WPRVFBZbf1CHowYNtZhX0ZojCIv1579Wz1t+on1H0WZxUGI4o5+Xusjw/ClnMU8iRh5U4/b0CipFhBM= alam.ashraful@L-BKASH-MAC-154